# Generated by Django 4.1.6 on 2023-02-10 03:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('donors', models.ManyToManyField(blank=True, to='entities.donor', verbose_name='Donor Agencies')),
                ('implementors', models.ManyToManyField(blank=True, to='entities.partner', verbose_name='Implementing Agencies')),
                ('partners', models.ManyToManyField(blank=True, to='entities.implementor', verbose_name='Accreditted Entities\\Partner Organizations')),
            ],
        ),
    ]
