# Generated by Django 4.1.6 on 2023-02-13 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(max_length=400, unique=True),
        ),
        migrations.AlterField(
            model_name='statuscategory',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
