# Generated by Django 4.1.6 on 2023-02-13 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_status_status_alter_statuscategory_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='rate',
            new_name='risk_rate',
        ),
    ]
