# Generated by Django 4.1.6 on 2023-02-10 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountrequest',
            options={'ordering': ['-created']},
        ),
    ]
